# Generated by Django 5.0.14 on 2026-07-29 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de tarea')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='entregables/', verbose_name='Archivo adjunto')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha límite de entrega')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='academico.asignatura')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la clase')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], max_length=10, verbose_name='Estado')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.inscripcion')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo académico')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.inscripcion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('inscripcion', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='EntregaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregas/', verbose_name='Archivo')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('retroalimentacion', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='evaluacion.entregable')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol__nombre': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de estudiante',
                'verbose_name_plural': 'Entregas de estudiantes',
                'unique_together': {('entregable', 'estudiante')},
            },
        ),
    ]
