# Generated by Django 5.0.14 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaestudiante',
            name='comentario_estudiante',
            field=models.TextField(blank=True, verbose_name='Comentario del estudiante'),
        ),
    ]
